# Generated by Django 5.0.6 on 2024-05-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_photo_car_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, default='cars/blank_photo.jpg', upload_to='cars/'),
        ),
    ]
